# bash_profile includes for Soma

eval $(keychain --eval --agents ssh,gpg -Q --quiet id_rsa)

if [ -f /usr/share/git/completion/git-prompt.sh ]; then
   . /usr/share/git/completion/git-prompt.sh
fi

export MATLAB_JAVA=/usr/lib/jvm/java-7-openjdk/jre
 
export PATH="$PATH:$HOME/.cabal/bin:$HOME/.rbenv/bin"
eval "$(rbenv init -)"

