#bash_profile includes for Trifid

module unload gcc
module load gcc/4.8.1
module load blas/1.0.248
module load openmpi-gcc/1.7.1
module load lapack/3.4.2

source ~/bin/git-prompt.sh

#override TERM if logging in from Soma
[ $TERM == "rxvt-unicode-256color" ] && export TERM=xterm-256color

PATH=~/bin/:$PATH
