#bash_profile includes for Trifid

module load openmpi-gcc/1.7.0
module load blas/1.0.248
module load lapack/3.4.2

export GULP_LIB=~/bin/gulpdata/Libraries
export GULP_DOC=~/bin/gulpdata/Docs

source ~/bin/git-prompt.sh

#override TERM if logging in from Soma
[ $TERM == "rxvt-unicode-256color" ] && export TERM=xterm-256color

PATH=~/bin/:$PATH
