#includes for Raijin's bash_profile

module load openmpi/1.6.3

export PATH=$PATH:~/scripts:~/scripts/calc_cell:~/bin:~/scripts/vt

source ~/bin/git-prompt.sh

#override TERM if logging in from Soma
[ $TERM == "rxvt-unicode-256color" ] && export TERM=xterm-256color
