#includes for Raijin's bash_profile

#source /etc/profile.d/nf_sh_modules

#umask 027

#module load dot 
#module load intel-cc

#module load intel-mkl
#module load intel-fc
#module load openmpi

export PATH=$PATH:~/scripts:~/scripts/calc_cell:~/bin:~/scripts/vt

source ~/bin/git-prompt.sh

#override TERM if logging in from Soma
[ $TERM == "rxvt-unicode-256color" ] && export TERM=xterm-256color
