#bash_profile includes for Jnana

#override TERM if logging in from Soma
[ $TERM == "rxvt-unicode-256color" ] && export TERM=xterm-256color

PATH=~/bin/:/cygdrive/c/Anaconda:/cygdrive/c/Anaconda/Scripts:/cygdrive/c/Users/e81365/AppData/Local/Julia-0.3.8/bin:$PATH

eval $(/usr/local/bin/ssh-pageant -r -a "/tmp/.ssh-pageant-$USERNAME")

source ~/bin/git-prompt.sh
