# bash_profile includes for Fenchurh

source ~/bin/git-prompt.sh

#override TERM if logging in from Soma
[ $TERM == "rxvt-unicode-256color" ] && export TERM=xterm-256color

export PATH=$HOME/.rbenv/bin:$PATH:/usr/local/cuda/bin/:$HOME/bin

eval "$(rbenv init -)"


