envoy -t ssh-agent 
source <(envoy -p)

source ~/bin/git-prompt.sh

export GOPATH=/home/tim/repos/gocode
export PATH=~/bin:$PATH:/home/tim/.cargo/bin:/usr/local/texlive/2015/bin/x86_64-linux:/home/tim/.gem/ruby/2.3.0/bin:$GOPATH/bin
export NOTI_PUSHBULLET_TOK=o.Rup9MFE3hwB2ovJjfOb4MVU4IsAzHymt
export NOTI_DEFAULT="pushbullet"
export GPG_TTY=$(tty)

alias fehsvg='feh --magick-timeout 1'
alias pcat='pygmentize -f terminal -O style=native -g'
alias svnaddall="svn status | grep '?' | sed 's/^.* /svn add /' | bash"
alias mdless='function _mdless(){ pandoc -s -f markdown -t man $@ | groff -T utf8 -man | less;};_mdless'
function md2pdf() { pandoc $1 --latex-engine=xelatex -o ${1%.md}.pdf --variable mainfont=Georgia; }

export keyboard=qwerty

eval "$(thefuck --alias)"

export CC=/opt/intel/composerxe/linux/bin/intel64/icc
export CXX=/opt/intel/composerxe/linux/bin/intel64/icpc

source /opt/intel/composerxe/linux/mkl/bin/mklvars.sh intel64

alias icmakepp='cmake -P /home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake icmake'
alias cmakepp='cmake -P /home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake'
alias pkg='cmake -P /home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake cmakepp_project_cli'
alias cml='cmake -P /home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake cmakelists_cli'
export CMAKEPP_PATH=/home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake
