envoy -t ssh-agent 
source <(envoy -p)

source ~/bin/git-prompt.sh

#Texlive and Ruby gems
export GOPATH=/home/tim/repos/gocode
export PATH=$PATH:/usr/local/texlive/2015/bin/x86_64-linux:/home/tim/.gem/ruby/2.3.0/bin:$GOPATH/bin
export NOTI_PUSHBULLET_TOK=o.Rup9MFE3hwB2ovJjfOb4MVU4IsAzHymt
export NOTI_DEFAULT="pushbullet"

alias fehsvg='feh --magick-timeout 1'
alias pcat='pygmentize -f terminal -O style=native -g'
alias svnaddall="svn status | grep '?' | sed 's/^.* /svn add /' | bash"

export keyboard=qwerty

eval "$(thefuck --alias)"

export CC=/opt/intel/composerxe/linux/bin/intel64/icc
export CXX=/opt/intel/composerxe/linux/bin/intel64/icpc

source /opt/intel/composerxe/linux/mkl/bin/mklvars.sh intel64

alias icmakepp='cmake -P /home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake icmake'
alias cmakepp='cmake -P /home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake'
alias pkg='cmake -P /home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake cmakepp_project_cli'
alias cml='cmake -P /home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake cmakelists_cli'
export CMAKEPP_PATH=/home/tim/Downloads/cmakepp/cmakepp/cmakepp.cmake
