[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# systemctl --user start bgchange.timer & #Start wallpaper changer
trayer --width 5 --transparent true --alpha 0 --tint 0x000000 --edge bottom --expand false --SetDockType false --distance 50 &

xmodmap -e "remove mod1 = Super_L"  # make sure X keeps it out of the mod1 group

xsetroot -cursor_name left_ptr
exec xmonad
